### ISSUE TITLE
Travailler sur une architecture résiliente et tolérante aux pannes

### ISSUE THREAD

**Issue by estrakio** [B4PTlSTE/transverse_CDA#6]

**Comment by B4PTlSTE** [comment]
Comparaison de Docker Swarm et Kubernetes et choix de Docker Swarm

**Comment by B4PTlSTE** [comment]
Désinstallation de Portainer et redéploiement de la machine virtuelle

**Comment by B4PTlSTE** [comment]
Docker Swarm initialisé et reverse proxy (load balancer / fail-over) déployé via nginx.
